// What a workflow demo says about its own data, in the sidebar and in its README.
//
// Decision 9 of the gallery plan: a demo states whether its data is generated, read from a source or
// both, and never fabricates BIM meaning. That sentence is written once here so all ten workflow
// demos carry the same one and a reader can compare them.

import { knownValue, propertyGroup, propertyRow, type PropertyGroup } from '@bim-open-toolkit/ui-gratify';
import type { WorkflowResult } from '@bim-open-toolkit/workflows';
import type { DataBasis } from '../../gallery/contracts.js';

// The sentence every workflow demo carries about what it shows.
export const honestyLine =
  'Gaps, conflicts and unresolved matches come from the fixture and stay visible. Nothing on this page is filled in, averaged, or read as zero.';

// What each basis means, in the words the README and the sidebar both use.
export const basisText: Readonly<Record<DataBasis, string>> = {
  synthetic: 'Generated by a seeded generator. The same seed gives the same gaps every run.',
  'source-backed': 'Read from a real file. What is missing is missing in the source.',
  mixed: 'Generated by default, with a real source available as an opt-in path.',
};

// What a workflow demo declares about its data: where it came from and what fixture it is.
export type WorkflowBasis = {
  readonly basis: DataBasis;
  readonly fixture: string;
  // Anything else this demo has to admit: a shimmed feature, an absent projection, a missing link.
  readonly caveats: readonly string[];
};

// The sidebar group that states the basis, the fixture, what the workflow could not decide, and the
// honesty line. Every workflow demo's inspector opens with it.
export const basisGroup = (result: WorkflowResult, declared: WorkflowBasis): PropertyGroup =>
  propertyGroup('basis', 'What this shows', [
    propertyRow('workflow', 'Workflow', knownValue(result.title)),
    propertyRow('fixture', 'Fixture', knownValue(declared.fixture)),
    propertyRow('basis', 'Data basis', knownValue(`${declared.basis}: ${basisText[declared.basis]}`)),
    propertyRow(
      'exceptions',
      'Could not be decided',
      knownValue(
        result.exceptions.length === 0
          ? 'nothing: every row was decided'
          : `${result.exceptions.length} rows, listed below with their reasons`,
      ),
    ),
    ...declared.caveats.map((text, index) => propertyRow(`caveat-${index}`, 'Note', knownValue(text))),
    propertyRow('honesty', 'Rule', knownValue(honestyLine)),
  ]);
